# Generated by Django 5.1 on 2024-08-17 17:25

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday_date', django_jalali.db.models.jDateField()),
                ('ceremony_datetime', django_jalali.db.models.jDateTimeField()),
                ('country', models.CharField(default='Iran', max_length=100)),
            ],
        ),
    ]
